### ISSUE TITLE
Review: peer-to-peer code review

### ISSUE THREAD

**Issue by oyelakinG9** [zhadier/Eme-Olympiad#2]

**Comment by oyelakinG9** [comment]
Good job 🎉🎉
Your code is neat and good 🙌🌹 There is nothing to say other than that 😍😍. Keep it up
![GOOD](https://media.giphy.com/media/3o6EhZPHqPvSRR8mxW/giphy.gif)

**Comment by Nicolaswg** [comment]
# Congrats you have done a great job
🦅 
- Good Project flow
- Excellent responsiveness interaction
- Interesting topic

## Recomendation 

> Try to use for each loop where it can be used, so them you can have lest lines of code
